#include"A0.h"
#include<cstdlib>
class stud_A4:public stud{
	public:
		stud_A4(){
			red_up-=40,blue_up+=0,white_up+=0;
			red=red_up,blue=blue_up,white=white_up;
			att-=5;
			py.push_back(19);
			ct1.push_back("敏捷");
			ct1.push_back("鼠叫");
			ct1.push_back("弱小");
			srand(time(nullptr));
			if(rand()*rand()%200==78){
				ct1.push_back("超能力者");
			}
			id=4;
			name="A04";
		}
};
